aws {
  api {
    base-url = "https://wo0r5itr98.execute-api.us-east-1.amazonaws.com"
    login-endpoint = ${aws.api.base-url}"/auth/login"
    register-endpoint = ${aws.api.base-url}"/auth/register"
    get-last-games = ${aws.api.base-url}"/games/recent"
    save-game = ${aws.api.base-url}"/games/save"
  }
}
